-- 여기는 관리자 화면입니다.

CREATE TABLESPACE myBTS DATAFILE'D:/bizwork/oracle/ordata/myBTS.dbf'
SIZE 100M AUTOEXTEND ON NEXT 100K;

CREATE USER mybts IDENTIFIED BY 1234 DEFAULT TABLESPACE myBTS;

GRANT DBA TO mybts;