-- 여기는 관리자 접속화면입니다.

-- TABLESPACE를 하나 생성
CREATE TABLESPACE myTBL1 DATAFILE 'D:/bizwork/oracle/ordata/mytbl_1.dbf' 
SIZE 100M
AUTOEXTEND ON NEXT 1M;

CREATE USER myMem IDENTIFIED BY 1234 DEFAULT TABLESPACE myTBL1;

GRANT DBA TO myMem;